[package]
name = "etfloader"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "etfloader"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.22.0"
erlang-term = "0.1.1"
